import type {
  User,
  Issue,
  IssueStatus,
  Comment,
  Attachment,
  TimelineEvent,
  InternalNote,
  TicketLog,
  Notification,
  KnowledgeArticle,
  Researcher,
  DashboardStats,
} from "@/lib/types";

const now = new Date();
const hoursAgo = (h: number) =>
  new Date(now.getTime() - h * 3600000).toISOString();
const daysAgo = (d: number) =>
  new Date(now.getTime() - d * 86400000).toISOString();

export const mockUsers: User[] = [
  {
    id: "u1",
    name: "Super Admin",
    email: "admin@jcsc.gov.jo",
    role: "ADMIN",
    team: "إدارة",
    isActive: true,
    createdAt: daysAgo(90),
  },
  {
    id: "u9",
    name: "دعم فني — إربد",
    email: "supervisor@jcsc.gov.jo",
    role: "SUPERVISOR",
    team: "الدعم الفني المراكز",
    isActive: true,
    createdAt: daysAgo(70),
  },
  { id: "u-hazem", name: "محمد حازم", email: "hazem@jcsc.gov.jo", role: "DEVELOPER", team: "Developer", isActive: true, createdAt: daysAgo(120) },
  { id: "u-hamza", name: "حمزة عياد", email: "hamza@jcsc.gov.jo", role: "DEVELOPER", team: "Developer", isActive: true, createdAt: daysAgo(110) },
  { id: "u-boran", name: "بوران عواد", email: "boran@jcsc.gov.jo", role: "DEVELOPER", team: "Developer", isActive: true, createdAt: daysAgo(100) },
  { id: "u-abdullah", name: "عبدالله مدغمش", email: "abdullah.m@jcsc.gov.jo", role: "DEVELOPER", team: "Developer", isActive: true, createdAt: daysAgo(95) },
  { id: "u-ahmad", name: "احمد موافي", email: "ahmad.m@jcsc.gov.jo", role: "DEVELOPER", team: "Developer", isActive: true, createdAt: daysAgo(90) },
  { id: "u-mohh", name: "محمد الحسن", email: "mohammad.h@jcsc.gov.jo", role: "DEVELOPER", team: "Developer", isActive: true, createdAt: daysAgo(85) },
  { id: "u-mustafa", name: "مصطفى اليوسف", email: "mustafa@jcsc.gov.jo", role: "DEVELOPER", team: "Developer", isActive: true, createdAt: daysAgo(80) },
  { id: "u-mohab", name: "محمد ابو باجة", email: "mohammad.ab@jcsc.gov.jo", role: "DEVELOPER", team: "Developer", isActive: true, createdAt: daysAgo(75) },
  { id: "u-mais", name: "ميس جابر", email: "mais@jcsc.gov.jo", role: "DEVELOPER", team: "Developer", isActive: true, createdAt: daysAgo(70) },
  { id: "u-mahmoud", name: "محمود مطاوع", email: "mahmoud@jcsc.gov.jo", role: "DEVELOPER", team: "Developer", isActive: true, createdAt: daysAgo(65) },
  { id: "u-ahmed-ay", name: "احمد اي", email: "ahmad.ay@jcsc.gov.jo", role: "DEVELOPER", team: "مدير فريق", isActive: true, createdAt: daysAgo(60) },
  { id: "u-abdelrahman", name: "عبدالرحمن العبد", email: "abdelrahman@jcsc.gov.jo", role: "DEVELOPER", team: "Developer", isActive: true, createdAt: daysAgo(60) },
];

export const mockIssues: Issue[] = [
  {
    id: "t1",
    number: "ISS-2026-001",
    title: "فشل تسجيل الدخول - مستخدم",
    description: "المستخدم لا يستطيع تسجيل الدخول بعد تحديث التطبيق",
    status: "RECEIVED",
    priority: "CRITICAL",
    governorate: "عمان",
    issueType: "تسجيل الدخول",
    team: "Developer",
    assigneeId: "u-hazem",
    reporterId: "u9",
    assigneeName: "محمد حازم",
    reporterName: "دعم فني — إربد",
    createdAt: hoursAgo(2),
    updatedAt: hoursAgo(1),
  },
  {
    id: "t2",
    number: "ISS-2026-002",
    title: "تأخر مزامنة البيانات - إربد",
    description: "البيانات لا تتزامن منذ 3 ساعات",
    status: "IN_PROGRESS",
    priority: "HIGH",
    governorate: "إربد",
    issueType: "مزامنة البيانات",
    team: "Database",
    assigneeId: "u-mohh",
    reporterId: "u9",
    assigneeName: "يونس صالح",
    reporterName: "دعم فني — إربد",
    createdAt: hoursAgo(5),
    updatedAt: hoursAgo(3),
  },
  {
    id: "t3",
    number: "ISS-2026-003",
    title: "خطأ GPS - الزرقاء",
    description: "الموقع غير دقيق في منطقة الزرقاء الجديدة",
    status: "NEED_INFO",
    priority: "MEDIUM",
    governorate: "الزرقاء",
    issueType: "GPS",
    team: "Developer",
    assigneeId: "u-hamza",
    reporterId: "u9",
    assigneeName: "حمزة عياد",
    reporterName: "دعم فني — إربد",
    createdAt: hoursAgo(8),
    updatedAt: hoursAgo(6),
  },
  {
    id: "t4",
    number: "ISS-2026-004",
    title: "تطبيق الميدان يتوقف - الكرك",
    status: "ASSIGNED",
    priority: "HIGH",
    governorate: "الكرك",
    issueType: "تطبيق الميدان",
    team: "Developer",
    assigneeId: "u-hazem",
    reporterId: "u9",
    assigneeName: "محمد حازم",
    reporterName: "دعم فني — إربد",
    createdAt: hoursAgo(12),
    updatedAt: hoursAgo(10),
  },
  {
    id: "t5",
    number: "ISS-2026-005",
    title: "GPS غير دقيق - البلقاء",
    status: "IN_PROGRESS",
    priority: "MEDIUM",
    governorate: "البلقاء",
    issueType: "GPS",
    team: "Developer",
    assigneeId: "u-hamza",
    reporterId: "u9",
    assigneeName: "حمزة عياد",
    reporterName: "دعم فني — إربد",
    createdAt: daysAgo(1),
    updatedAt: hoursAgo(4),
  },
  {
    id: "t6",
    number: "ISS-2026-006",
    title: "خطأ في الاستبيان - معان",
    status: "READY_FOR_TESTING",
    priority: "LOW",
    governorate: "معان",
    issueType: "الاستبيان",
    team: "Developer",
    assigneeId: "u-hazem",
    reporterId: "u9",
    assigneeName: "محمد حازم",
    reporterName: "دعم فني — إربد",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
  },
  {
    id: "t7",
    number: "ISS-2026-007",
    title: "جهاز Tablet لا يعمل - الطفيلة",
    status: "RECEIVED",
    priority: "LOW",
    governorate: "الطفيلة",
    issueType: "الأجهزة",
    team: "Developer",
    assigneeId: "u-hazem",
    reporterId: "u9",
    assigneeName: "محمد حازم",
    reporterName: "دعم فني — إربد",
    createdAt: daysAgo(1),
    updatedAt: hoursAgo(20),
  },
  {
    id: "t8",
    number: "ISS-2026-008",
    title: "فشل الاتصال بقاعدة البيانات",
    status: "WAITING_DEPLOYMENT",
    priority: "CRITICAL",
    governorate: "عمان",
    issueType: "مزامنة البيانات",
    team: "Database",
    assigneeId: "u-mohh",
    reporterId: "u1",
    assigneeName: "يونس صالح",
    reporterName: "Super Admin",
    createdAt: hoursAgo(1),
    updatedAt: hoursAgo(0.5),
  },
  {
    id: "t9",
    number: "ISS-2026-009",
    title: "بطء في تحميل التطبيق - جرش",
    status: "CLOSED",
    priority: "MEDIUM",
    governorate: "جرش",
    issueType: "تطبيق الميدان",
    team: "DevOps",
    assigneeId: "u-mustafa",
    reporterId: "u9",
    assigneeName: "مصطفى اليوسف",
    reporterName: "دعم فني — إربد",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(2),
  },
  {
    id: "t10",
    number: "ISS-2026-010",
    title: "تسجيل دخول متكرر - عجلون",
    status: "ASSIGNED",
    priority: "HIGH",
    governorate: "عجلون",
    issueType: "تسجيل الدخول",
    team: "Developer",
    assigneeId: "u-hazem",
    reporterId: "u9",
    assigneeName: "محمد حازم",
    reporterName: "دعم فني — إربد",
    createdAt: hoursAgo(3),
    updatedAt: hoursAgo(2),
  },
];

/** @deprecated Use mockIssues */
export const mockTickets = mockIssues;

export const mockComments: Comment[] = [
  {
    id: "c1",
    content: "تم التواصل مع المستخدم وطلب إعادة تشغيل التطبيق",
    ticketId: "t1",
    authorId: "u-hazem",
    authorName: "محمد حازم",
    createdAt: hoursAgo(1.5),
  },
  {
    id: "c2",
    content: "المشكلة مستمرة بعد إعادة التشغيل",
    ticketId: "t1",
    authorId: "u9",
    authorName: "دعم فني — إربد",
    createdAt: hoursAgo(1),
  },
  {
    id: "c3",
    content: "جاري التحقق من سجلات الخادم",
    ticketId: "t2",
    authorId: "u6",
    authorName: "يونس صالح",
    createdAt: hoursAgo(4),
  },
];

export const mockAttachments: Attachment[] = [
  {
    id: "a1",
    name: "screenshot-login-error.png",
    url: "/placeholder-screenshot.png",
    ticketId: "t1",
    createdAt: hoursAgo(1.8),
  },
  {
    id: "a2",
    name: "sync-log.txt",
    url: "/placeholder-log.txt",
    ticketId: "t2",
    createdAt: hoursAgo(4.5),
  },
];

export const mockTimeline: TimelineEvent[] = [
  {
    id: "tl1",
    action: "إنشاء التذكرة",
    details: "تم إنشاء التذكرة من الدعم الفني المراكز",
    ticketId: "t1",
    createdAt: hoursAgo(2),
  },
  {
    id: "tl2",
    action: "تعيين مسؤول",
    details: "تم تعيين محمد حازم",
    ticketId: "t1",
    createdAt: hoursAgo(1.8),
  },
  {
    id: "tl3",
    action: "تغيير الحالة",
    details: "من مفتوحة إلى قيد المعالجة",
    ticketId: "t1",
    createdAt: hoursAgo(1.5),
  },
  {
    id: "tl4",
    action: "إضافة تعليق",
    ticketId: "t1",
    createdAt: hoursAgo(1),
  },
];

export const mockInternalNotes: InternalNote[] = [
  {
    id: "n1",
    content: "يبدو أن المشكلة مرتبطة بتحديث OAuth الأخير",
    ticketId: "t1",
    authorId: "u6",
    authorName: "يونس صالح",
    createdAt: hoursAgo(0.8),
  },
];

export const mockLogs: TicketLog[] = [
  {
    id: "l1",
    level: "error",
    message: "Authentication failed: invalid token",
    ticketId: "t1",
    createdAt: hoursAgo(2),
  },
  {
    id: "l2",
    level: "warning",
    message: "Retry attempt 3/5 for sync",
    ticketId: "t1",
    createdAt: hoursAgo(1.5),
  },
  {
    id: "l3",
    level: "info",
    message: "User session created",
    ticketId: "t1",
    createdAt: hoursAgo(1),
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "not1",
    title: "تذكرة حرجة جديدة",
    message: "JCSC-2026-001 - فشل تسجيل الدخول",
    isRead: false,
    userId: "u1",
    createdAt: hoursAgo(2),
  },
  {
    id: "not2",
    title: "تصعيد تذكرة",
    message: "JCSC-2026-008 تم تصعيدها إلى قاعدة البيانات",
    isRead: false,
    userId: "u1",
    createdAt: hoursAgo(1),
  },
  {
    id: "not3",
    title: "تذكرة محلولة",
    message: "JCSC-2026-006 تم حلها بنجاح",
    isRead: true,
    userId: "u1",
    createdAt: hoursAgo(24),
  },
  {
    id: "not4",
    title: "مستخدم بدون Sync",
    message: "15 مستخدماً لم يقوموا بالمزامنة منذ 24 ساعة",
    isRead: false,
    userId: "u1",
    createdAt: hoursAgo(6),
  },
  {
    id: "not5",
    title: "تحديث النظام",
    message: "تم نشر الإصدار 2.1.0 بنجاح",
    isRead: true,
    userId: "u1",
    createdAt: daysAgo(2),
  },
];

export const mockKnowledgeArticles: KnowledgeArticle[] = [
  {
    id: "kb1",
    title: "حل مشكلة تسجيل الدخول",
    content:
      "1. تأكد من اتصال الإنترنت\n2. امسح ذاكرة التطبيق\n3. أعد تثبيت التطبيق\n4. تواصل مع الدعم إذا استمرت المشكلة",
    category: "تسجيل الدخول",
    tags: ["login", "auth", "password"],
    createdAt: daysAgo(30),
    updatedAt: daysAgo(5),
  },
  {
    id: "kb2",
    title: "إصلاح مشاكل المزامنة",
    content:
      "تحقق من:\n- قوة الإشارة\n- مساحة التخزين\n- آخر وقت Sync\n- إعادة تشغيل الجهاز",
    category: "المزامنة",
    tags: ["sync", "data", "offline"],
    createdAt: daysAgo(25),
    updatedAt: daysAgo(3),
  },
  {
    id: "kb3",
    title: "معايرة GPS",
    content: "افتح الإعدادات > الموقع > معايرة GPS > اتبع التعليمات على الشاشة",
    category: "GPS والموقع",
    tags: ["gps", "location", "calibration"],
    createdAt: daysAgo(20),
    updatedAt: daysAgo(10),
  },
  {
    id: "kb4",
    title: "استكشاف أخطاء التطبيق",
    content: "Force stop > Clear cache > Restart app. إذا لم ينجح، أعد التثبيت.",
    category: "التطبيق",
    tags: ["app", "crash", "restart"],
    createdAt: daysAgo(15),
    updatedAt: daysAgo(2),
  },
  {
    id: "kb5",
    title: "صيانة أجهزة Tablet",
    content: "تنظيف الشاشة، تحديث النظام، شحن كامل قبل المزامنة",
    category: "الأجهزة",
    tags: ["tablet", "hardware", "maintenance"],
    createdAt: daysAgo(10),
    updatedAt: daysAgo(1),
  },
  {
    id: "kb6",
    title: "دليل المستخدم الميداني",
    content: "دليل شامل للمستخدمين يغطي جميع العمليات اليومية",
    category: "عام",
    tags: ["guide", "field", "researcher"],
    createdAt: daysAgo(60),
    updatedAt: daysAgo(7),
  },
];

export const mockResearchers: Researcher[] = [
  {
    id: "r1",
    name: "عبدالله الحمود",
    governorate: "عمان",
    status: "ACTIVE",
    lastSyncAt: hoursAgo(0.5),
    lastActiveAt: hoursAgo(0.2),
  },
  {
    id: "r2",
    name: "مريم السعد",
    governorate: "إربد",
    status: "ACTIVE",
    lastSyncAt: hoursAgo(1),
    lastActiveAt: hoursAgo(0.5),
  },
  {
    id: "r3",
    name: "طارق البطار",
    governorate: "الزرقاء",
    status: "IDLE",
    lastSyncAt: hoursAgo(5),
    lastActiveAt: hoursAgo(8),
  },
  {
    id: "r4",
    name: "سميرة الخالدي",
    governorate: "البلقاء",
    status: "NO_SYNC",
    lastSyncAt: hoursAgo(30),
    lastActiveAt: hoursAgo(12),
  },
  {
    id: "r5",
    name: "وليد المصري",
    governorate: "الكرك",
    status: "NO_SYNC",
    lastSyncAt: hoursAgo(48),
    lastActiveAt: hoursAgo(24),
  },
  {
    id: "r6",
    name: "رانيا العبدالله",
    governorate: "معان",
    status: "ACTIVE",
    lastSyncAt: hoursAgo(2),
    lastActiveAt: hoursAgo(1),
  },
  {
    id: "r7",
    name: "سامي الراشد",
    governorate: "جرش",
    status: "IDLE",
    lastSyncAt: hoursAgo(6),
    lastActiveAt: hoursAgo(10),
  },
  {
    id: "r8",
    name: "دiana Khoury",
    governorate: "العقبة",
    status: "ACTIVE",
    lastSyncAt: hoursAgo(0.8),
    lastActiveAt: hoursAgo(0.3),
  },
];

const OPEN_ISSUE_STATUSES: IssueStatus[] = [
  "RECEIVED",
  "ASSIGNED",
  "IN_PROGRESS",
  "NEED_INFO",
  "WAITING_DEPLOYMENT",
  "READY_FOR_TESTING",
  "RETURNED",
];

export const mockDashboardStats: DashboardStats = {
  openIssues: mockIssues.filter((t) => OPEN_ISSUE_STATUSES.includes(t.status)).length,
  openTickets: mockIssues.filter((t) => OPEN_ISSUE_STATUSES.includes(t.status)).length,
  critical: mockIssues.filter(
    (t) => t.priority === "CRITICAL" && t.status !== "CLOSED"
  ).length,
  high: mockIssues.filter(
    (t) => t.priority === "HIGH" && t.status !== "CLOSED"
  ).length,
  medium: mockIssues.filter(
    (t) => t.priority === "MEDIUM" && t.status !== "CLOSED"
  ).length,
  low: mockIssues.filter(
    (t) => t.priority === "LOW" && t.status !== "CLOSED"
  ).length,
  todayIssues: 7,
  topCategories: [
    { type: "تسجيل الدخول", count: 12 },
    { type: "مزامنة البيانات", count: 9 },
    { type: "GPS", count: 7 },
    { type: "تطبيق الميدان", count: 5 },
    { type: "الأجهزة", count: 3 },
  ],
  topIssues: [
    { type: "تسجيل الدخول", count: 12 },
    { type: "مزامنة البيانات", count: 9 },
    { type: "GPS", count: 7 },
    { type: "تطبيق الميدان", count: 5 },
    { type: "الأجهزة", count: 3 },
  ],
  chartData: [
    { date: "26/7", count: 4 },
    { date: "27/7", count: 7 },
    { date: "28/7", count: 5 },
    { date: "29/7", count: 9 },
    { date: "30/7", count: 6 },
    { date: "31/7", count: 11 },
    { date: "1/8", count: 7 },
  ],
};

export const currentUser = mockUsers[0];
